import os
os.system ('clear')
os.system ('pkg install python -y')
os.system ('pkg install python2 -y')
os.system ('pkg install python3 -y')
os.system ('clear')
print ('please wait...')
os.system ('pip install Amino.py')
os.system ('clear')
os.system ('pkg install bash')
os.system ('pkg install clang')
os.system ('clear')
os.system ('pkg install ruby')
os.system ('pkg install git')
os.system ('pkg install php')
os.system ('clear')
os.system ('pkg install tor')
os.system ('pkg install nmap')
os.system ('pkg install zip')
os.system ('pkg install unzip')
os.system ('pkg install tar')
os.system ('clear')
os.system ('pkg install macchanger')
os.system ('pkg install wget')
os.system ('pkg install bmon')
os.system ('clear')
print ('1)xerxes')
print ('2)metasploit')
print ('3)InviteAmino')
print ('4)hunner')
print ('5)Gurdan')
en = input ('Enter Number:  ')
if en == 1:
	os.system ('git clone https://github.com/XCHADXFAQ77X/XERXES')
	os.system ('cd xerxes')
	os.system ('gcc -o xerxes xerxes.c')
elif en == 2:
	os.system ('wget https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master/metasploit.sh')
elif en == 3:
	os.system ('git clone https://github.com/kira-xc/AminoInvite')
elif en == 4:
	os.system ('git clone https://github.com/b3-v3r/Hunner')
	os.system ('cd Hunner')
	os.system ('chmod +x *')
elif en == 5:
	os.system('git clone https://github.com/methaza/guardn')
else:
	print ('Sorry')